### ISSUE TITLE
SwingWorker for reading QR code

### ISSUE THREAD

**Issue by malloxpb** [vietabroader/VAQR#17]

**Comment by ctring** [comment]
Thank you for opening this issue. Just a few pointers to make sure that we are going to the right direction:

Make a controller for this similar to `AuthenticationController`. 
There is example code for this [here](https://github.com/sarxos/webcam-capture/blob/7e82df6ba87cdff3edfc4c8318ac0f0769db4a4a/webcam-capture-examples/webcam-capture-qrcode/src/main/java/com/github/sarxos/webcam/WebcamQRCodeExample.java). The demo can be found [here](https://github.com/sarxos/webcam-capture/tree/7e82df6ba87cdff3edfc4c8318ac0f0769db4a4a/webcam-capture-examples/webcam-capture-qrcode)

**Comment by ctring** [comment]
For now when you detect a QR code. Just log it using the logger. Look into GoogleAPIUtils file to see how to use a logger.

**Comment by ctring** [comment]
There've been some changes in the codebase. You should put the QR reading code in `WebcamController`.
Do necessary initialization of this controller in `WebcamView`. 
Also, look into `AuthenticationController` for an example of `SwingWorker`. For QR reading, however, we need to use `publish` and `process` method of `SwingWorker`. 
The types of our `SwingWorker` should be `SwingWorker<Integer, String>`
We use `publish` to publish the recognized text. In `process`, we'll only log this text for now.
In `done()` we should stop the webcam panel. Now, we don't need to stop the webcam panel on webcam frame closing; instead, we'll call `worker.cancel(true)` there. In `doInBackground()` we should check whether `isCancelled()` is true and exit accordingly.

**Comment by malloxpb** [comment]
I will work on that right now :)

**Comment by malloxpb** [comment]
I will summarize what I think I need to do and some of my questions just to know if I am going on the right track:
1. We will need to create a webcamPanel, webcam reference in the controller so that we can call them in the view. The purpose is to use them for closing panel condition/checking if the webcam is available
2. Implement the QR code reader, which is going into the doInBackground() function, it will return an Integer. However, I don't really get what the next step is. Is it going to verify the data from the QR code to see if it is in the spreadsheet, then print to the console/textarea true/false? And printing output will be in the process() function right? Since it is going to return a list of string.
3. When the user close the panel, the loop in doInBackground() for reading QR stops by checking if the worker has been cancelled. We can do this by using worker.cancel(true) in the done() with the condition of closing the panel.
4. Are we going to use logger for printing messages?
Please let me know if I am wrong. I am also sorry for the late progress on this task...

**Comment by ctring** [comment]
1. Yes
2. The worker doesn't need to return anything. For starter, just focus on the `doInBackground()` method and don't care about `process()`, `publish()`, or `done()`. In this method, you need to have an indefinite loop that would read the code from webcam and print it out using logger without verification or anything. 
3. On the panel close event, call `worker.cancel(true)` to set the worker cancel flag to true. We check this flag in the loop inside `doInbackground()`, using `isCancelled()`. `done()` should not have anything to do with this cancellation logic. 
4. Yes, for debugging purpose.

**Comment by malloxpb** [comment]
I have successfully implemented the QR reading code and I got the URL from it. I am just wondering what we have to do in order to execute that data...
