### ISSUE TITLE
Controller for refreshing a sheet

### ISSUE THREAD

**Issue by ctring** [vietabroader/VAQR#20]
Call this controller `SheetRefreshController`

Get yourself familiar with VASpreadsheet

This controller should handle the click event of the Refresh button:
- First, write a method to remove all column names in `columnNameToChar`. Then use this method on the current `VASpreadsheet` (get this object in `GlobalState`).
- Set the new sheet name, column names, row ranges, from the input text fields to the current spreadsheet.
- Call `refreshAllColumn()`. Preferably wrap this method in a `SwingWorker`. (Look into `AuthenticationController` for example).
- When refreshing completes, put a message in `lblSheetMessage` saying that the sheet is refreshed with a timestamp.

**Comment by ctring** [comment]
Note that we disable Secret column for now. Just treat it as if it's not there.

**Comment by ctring** [comment]
Please do #21 before this

**Comment by ellienguyen** [comment]
Should I put the method to remove all column names in VASpreadsheet?

**Comment by ctring** [comment]
yes
