### ISSUE TITLE
Cannot sign in in my computer

### ISSUE THREAD

**Issue by ellienguyen** [vietabroader/VAQR#27]
![image](https://user-images.githubusercontent.com/18899970/27695793-85513058-5cb5-11e7-85b1-0e6af2887c1c.png)
![image](https://user-images.githubusercontent.com/18899970/27695802-8c8e0aee-5cb5-11e7-82c6-26d4095fdc82.png)
Here is what it is shown in my terminal when I run `gradle test` and `gradle run` @ctring

**Comment by ctring** [comment]
do you have the client_secret.json in the resource folder?

**Comment by ellienguyen** [comment]
I don't have the resource folder. Here is the screenshot of my files:
![image](https://user-images.githubusercontent.com/18899970/27702801-dd9d777a-5cca-11e7-902e-06152038d87c.png)

**Comment by ctring** [comment]
It's in `src/main/resources`
Go to [API Manager](https://console.cloud.google.com/apis/credentials?project=vietabroader-qr&authuser=1), download the **VAQR Desktop App** credential, rename the file to `client_secret.json` then put it there.

**Comment by ellienguyen** [comment]
It is solved. Thank you
