### ISSUE TITLE
Add Webcam panel with no logic

### ISSUE THREAD

**Issue by ctring** [vietabroader/VAQR#3]
Add to Gradle dependencies:
```
compile group: 'com.github.sarxos', name:'webcam-capture', version: '0.3.10'
```

This library provides a WebcamPanel component:
```
import com.github.sarxos.webcam.WebcamPanel;
```

Put this component into the "Scan QR Code" panel. Use `setPreferredSize()` method to set to an appropriate size.

Github of the webcam library (not really needed for this task but to provide some context): https://github.com/sarxos/webcam-capture

**Comment by ctring** [comment]
Github of the webcam library: https://github.com/sarxos/webcam-capture

**Comment by malloxpb** [comment]
So this task is basically adding function to the Start Webcam button, which is opening the camera window by using WebcamPanel right?

**Comment by ctring** [comment]
WebcamPanel is a component just like a button or a text field, and you can put it directly into the main window without opening a new window. There are multiple options for this tasks, in increasing order of difficulty:

1. Only put a WebcamPanel into the "Scan QR Code panel". This is what I originally mean in the description of this task
2. Do (1) and also add function to the Start Webcam button to start the webcam. Click it again to stop the webcam
3. Instead of putting the WebcamPanel in the main Window, when clicking on the Start Webcam button, a new window with the WebcamPanel will appear. Turn the window off to stop the webcam.

You can choose one of these 3 options based on how comfortable you are with Swing and Java in general.
