### ISSUE TITLE
Upload image for README

### ISSUE THREAD

**Issue by ellienguyen** [vietabroader/VAQR#36]
![image](https://user-images.githubusercontent.com/18899970/27970474-a43c7260-6314-11e7-925d-4d9e8955d1b3.png)
![image](https://user-images.githubusercontent.com/18899970/27970497-b85dfa02-6314-11e7-859d-998f53f7bf01.png)
![image](https://user-images.githubusercontent.com/18899970/27970654-43c24cba-6315-11e7-91ed-945db7bc16a7.png)
![image](https://user-images.githubusercontent.com/18899970/27970797-b5793c56-6315-11e7-92f1-37653e638021.png)
![image](https://user-images.githubusercontent.com/18899970/27971334-f8dc01ac-6317-11e7-98c3-cf50efc5400f.png)
![image](https://user-images.githubusercontent.com/18899970/27971357-09bb7dc2-6318-11e7-8999-4f91a6e057a9.png)
![image](https://user-images.githubusercontent.com/18899970/27972274-66e6bfa4-631b-11e7-9309-463cda05a5be.png)
![image](https://user-images.githubusercontent.com/18899970/27972322-8d2b45fe-631b-11e7-8740-693e46f06b75.png)

**Comment by ellienguyen** [comment]
![image](https://user-images.githubusercontent.com/18899970/27972377-c85c576c-631b-11e7-9c7b-4f96db21410d.png)
![image](https://user-images.githubusercontent.com/18899970/27972421-ed952c0c-631b-11e7-9044-c1ce6513c394.png)

**Comment by ctring** [comment]
test comment after close

**Comment by ctring** [comment]
<img width="542" alt="screen shot 2017-07-10 at 10 24 11 pm" src="https://user-images.githubusercontent.com/6244849/28052399-cddefe14-65bf-11e7-9666-07bfdc7189c4.png">
<img width="444" src="https://user-images.githubusercontent.com/6244849/28052466-4082d058-65c0-11e7-9e93-e9839c1d6242.png">
